name: non production environment 
on:
  push:
    branches: ["feature-initial-page"]
env:
  bucket_name: cfst-3457-2a87aa6b679b7799385e61cbf-nonprodbucket-d8s0awa43td2
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: copy buckets
        run: aws s3 sync ./ s3://$bucket_name/

